version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./:/var/www

  webserver:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app


